# name: Deploy to VM

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.7.0
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Add VM to known hosts
#         run: |
#           mkdir -p ~/.ssh
#           ssh-keyscan ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

#       - name: Deploy to VM
#         run: |
#           ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "cd ${{ secrets.PROJECT_PATH }} && \
#           git pull && \
#           docker-compose down && \
#           docker-compose build && \
#           docker-compose up -d"
